language: node_js
node_js:
- node

branches:
  only:
  - master

deploy:
  provider: s3
  bucket: klarna-decision-services
  skip_cleanup: true
  region: eu-central-1
  local_dir: html
  on:
    branch: master
  dot_match: true
  secret_access_key:
    secure: JqV6hyC9bc34T0I523poaDmagE5V5NxBWOEnUHEJ8z5bjqYsIiVrSMwdDFnWkO3TtI8Qd9JZ8AXkP0rz2DfNbb0FrSFg79Nlzu1UjDZZQ8qlGRjlVb+L35Bp6nKwoaXnQhrh/qbeCmWKB0Uno4U5XV2mbTjuHT5o1JAS4DKyAX/64aj+ETpDqc9Fqy5ejf6Y5vKNFuYDj5NqcfYA49pwKUEl4AC5cjrRQFdXGL+LM7ARWtQvYRs+IaTUFACXxpDUoSWRCHk2LTlU+QBvWIPghBUa1dMEe60ukDz9et0xC2N/B3MeduF0UlzPTd5E9LA9zFFH6G6MlxMPP3pOGdF+jw/hWYSYKcivav9dFcwietjodrTNdNX4fpLd7Y2OPauceC81pz5pweIesDBlMb8C0T4WRwxuZVZLzLukYkCB5cyBizkDoC3YJZdnjjJmlkSOZWTa4ACbAORwIEJzwettGxBYFA+5sLiBHN4g9FvkSDofPx0/d2JM6ImQ9NRVVgBiI4ZALJQbqlrDR1XizF3zZK029FV3ZIrEzBXbYyKUuaEJHcIqS+8/UaB8eE6GilWfgxzAe6GJDQ1F1B8gIlW7PY/XqeLa6aWcSsysLsFkzgqXFsyZgecW63k3xJ+m8XwffKyxLk0GF8ntfylsVzVq5a7mBcQLbkN64IqJxSmJSzY=
  acl: public_read

